# Use your local ml-pipeline image
FROM hamzachaieb01/ml-pipeline:latest

# Set working directory
WORKDIR /app

# Copy application files (assuming they aren't already in the base image)
COPY streamlit_app.py .
COPY artifacts/ /app/artifacts/

# Expose port 8501
EXPOSE 8501

# Command to run Streamlit
CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
