# Use your local ml-pipeline image
FROM hamzachaieb01/ml-pipeline:latest

# Set working directory
WORKDIR /app

# Copy application files (assuming they aren't already in the base image)
COPY app.py .
COPY artifacts/ /app/artifacts/

# Expose port 8000
EXPOSE 8000

# Command to run FastAPI
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
