# Use your local ml-pipeline image
FROM hamzachaieb01/ml-pipeline:latest

# Set working directory
WORKDIR /app

# Copy application files (assuming they aren't already in the base image)
COPY mlflow.db .
COPY artifacts/ /app/artifacts/

# Expose port 5001
EXPOSE 5001

# Command to run MLflow UI
CMD ["mlflow", "ui", "--backend-store-uri", "sqlite:///mlflow.db", "--port", "5001", "--host", "0.0.0.0"]
