global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fastapi:8000']

  - job_name: 'mlflow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mlflow:5001']
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']