global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 5s

rule_files:
  - "rules/ml_alerts.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['fastapi:8000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop

  - job_name: 'mlflow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mlflow:5001']
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']