name: ML Pipeline CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker images
        run: |
          docker compose build

      - name: Verify FastAPI image
        run: |
          docker run --name test-fastapi -d ml_pipeline-fastapi
          sleep 5
          docker logs test-fastapi
          docker rm -f test-fastapi

      - name: Run Docker Compose
        run: |
          docker compose up -d
          echo "Waiting for services to start (30 seconds)..."
          sleep 30
          echo "Container status:"
          docker compose ps
      
      - name: Debug container logs
        run: |
          echo "=== FastAPI container logs ==="
          docker compose logs fastapi
          echo "=== MLflow container logs ==="
          docker compose logs mlflow
          echo "=== Pipeline container logs ==="
          docker compose logs pipeline
      
      - name: Test FastAPI
        run: |
          for i in {1..5}; do
            echo "Attempt $i: Checking FastAPI health..."
            if curl -s http://localhost:8000/health | grep -q "healthy"; then
              echo "FastAPI is healthy!"
              break
            fi
            if [ $i -eq 5 ]; then
              echo "FastAPI health check failed after 5 attempts"
              docker compose logs fastapi
              exit 1
            fi
            echo "Waiting 5 seconds before next attempt..."
            sleep 5
          done
      
      - name: Check Streamlit logs
        run: |
          if docker compose logs streamlit | grep -q "Streamlit server is running" || docker compose logs streamlit | grep -q "You can now view your Streamlit app in your browser"; then
            echo "Streamlit is running properly"
          else
            echo "Streamlit server check failed, showing logs:"
            docker compose logs streamlit
            exit 1
          fi
      
      - name: Check MLflow logs
        run: |
          if docker compose logs mlflow | grep -q "Listening at:"; then
            echo "MLflow is running properly"
          else
            echo "MLflow server check failed, showing logs:"
            docker compose logs mlflow
            exit 1
          fi
      
      - name: Verify Pipeline execution
        run: |
          echo "Checking pipeline execution status..."
          PIPELINE_STATUS=$(docker inspect ml_pipeline-pipeline-1 --format='{{.State.ExitCode}}')
          if [ "$PIPELINE_STATUS" -eq 0 ]; then
            echo "Pipeline executed successfully"
            docker compose logs pipeline
          else
            echo "Pipeline execution failed with exit code $PIPELINE_STATUS, showing logs:"
            docker compose logs pipeline
            exit 1
          fi
      
      - name: Stop Docker Compose
        if: always()
        run: |
          docker compose down