name: ML Pipeline CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Start services
        run: |
          docker compose up -d
          echo "Waiting for services to start (30 seconds)..."
          sleep 30
          echo "Container status:"
          docker compose ps

      - name: Check FastAPI health
        run: |
          for i in {1..5}; do
            echo "Attempt $i: Checking FastAPI health..."
            if curl -s http://localhost:8000/health | grep -q "healthy"; then
              echo "FastAPI is healthy!"
              break
            fi
            if [ $i -eq 5 ]; then
              echo "FastAPI health check failed after 5 attempts"
              docker compose logs fastapi
              exit 1
            fi
            echo "Waiting 5 seconds before next attempt..."
            sleep 5
          done

      - name: Check Streamlit
        run: |
          if docker compose logs streamlit | grep -q "You can now view your Streamlit app in your browser"; then
            echo "Streamlit is running properly"
          else
            echo "Streamlit server check failed, showing logs:"
            docker compose logs streamlit
            exit 1
          fi

      - name: Check MLflow
        run: |
          if docker compose logs mlflow | grep -q "Listening at:"; then
            echo "MLflow is running properly"
          else
            echo "MLflow server check failed, showing logs:"
            docker compose logs mlflow
            exit 1
          fi

      - name: Verify Pipeline execution
        run: |
          echo "Checking pipeline execution status..."
          PIPELINE_STATUS=$(docker inspect ml_pipeline-pipeline-1 --format='{{.State.ExitCode}}')
          if [ "$PIPELINE_STATUS" -eq 0 ]; then
            echo "Pipeline executed successfully"
            docker compose logs pipeline
          else
            echo "Pipeline execution failed with exit code $PIPELINE_STATUS, showing logs:"
            docker compose logs pipeline
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-artifacts
          path: ./artifacts/
          if-no-files-found: warn

      - name: Expose services with ngrok (5 minutes only)
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          echo "Installing ngrok to expose MLflow and Streamlit..."
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok
          ngrok authtoken $NGROK_AUTH_TOKEN
          ngrok http 5001 > /dev/null &
          ngrok http 8501 > /dev/null &
          sleep 20  # Increased to 20 seconds to ensure services are ready
          echo "Raw ngrok tunnels:"
          curl -s http://localhost:4040/api/tunnels
          MLFLOW_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels | map(select(.config.addr == "http://localhost:5001"))[0].public_url')
          STREAMLIT_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels | map(select(.config.addr == "http://localhost:8501"))[0].public_url')
          if [ "$MLFLOW_URL" = "null" ] || [ "$STREAMLIT_URL" = "null" ]; then
            echo "Error: One or both ngrok URLs are null. Showing detailed logs:"
            docker compose logs mlflow
            docker compose logs streamlit
            exit 1
          fi
          echo "MLflow URL: $MLFLOW_URL"
          echo "Streamlit URL: $STREAMLIT_URL"
          echo "MLFLOW_URL=$MLFLOW_URL" >> $GITHUB_ENV
          echo "STREAMLIT_URL=$STREAMLIT_URL" >> $GITHUB_ENV
          echo "Services are running. Access MLflow at $MLFLOW_URL and Streamlit at $STREAMLIT_URL for the next 5 minutes."
          sleep 300  # Keep alive for 5 minutes (300 seconds)

      - name: Cleanup
        if: always()
        run: docker compose down